/**
 * home-data.js — single source of truth for all public-facing page data.
 *
 * Loaded as a plain <script> (NOT type="module") on home.html, submit-entry.html,
 * and nominate.html, so the data is available synchronously before the page
 * scripts run.  When you add a new sector, category, region, or county/city,
 * update this ONE file — every page updates automatically.
 *
 * Sets:
 *   window.BTA_HOME_DATA      — full structured object (used by home.html)
 *   window.REGION_DATA        — 3-level region hierarchy (submit-entry.js, nominate.js)
 *   window.SECTORS            — flat sector name array (config.js backward compat)
 *   window.STANDARD_CATEGORIES — sector→categories map (config.js backward compat)
 */
(function () {
  'use strict';

  /* ─────────────────────────────────────────────
     1. SECTORS & CATEGORIES
     Mirrors STANDARD_CATEGORIES in config.js.
     To add/remove categories: edit this object.
     To add a new sector: add a new key + entry in SECTOR_META below.
  ───────────────────────────────────────────── */
  const SECTOR_CATEGORIES = {
    'BUILDING & CONSTRUCTION': [
      'Brickwork & Masonry Company',
      'Drainage Company',
      'Extension Company',
      'General Building Company',
      'Groundworks & Foundations Company',
      'Guttering Company',
      'Loft Conversion Company',
      'Maintenance Services',
      'New Build Company',
      'Roofing Company',
      'Structural Engineers',
      'Structural Steelworks',
    ],
    'MECHANICAL, ELECTRICAL & PLUMBING': [
      'Air-Conditioning & Ventilation Company',
      'Electrical Company',
      'Heating Company',
      'Plumbing Company',
      'Underfloor Heating Company',
    ],
    'CARPENTRY & JOINERY': [
      'Cabinet Maker',
      'Carpentry Company',
      'Joinery Company',
      'Staircase Specialist',
      'Timber Windows Installer',
    ],
    'INTERIOR FIT-OUT & FINISHING': [
      'Bathroom Installer',
      'Carpet Fitters',
      'Curtains & Blinds Installer',
      'Drylining Company',
      'Flooring Installer',
      'Home Office Installer',
      'Interior Refurbishment Company',
      'Kitchen Installer',
      'Painting & Decorating Company',
      'Plastering Company',
      'Screeding Company',
      'Tiling Installer',
    ],
    'OUTDOOR & LANDSCAPING': [
      'Decking Company',
      'Driveway & Paving Company',
      'Fencing Installer',
      'Gardening Services',
      'Garden Outbuilding Company',
      'Landscaping & Garden Design Company',
      'Outdoor Lighting & Electrical Company',
      'Tree Surgery Services',
    ],
    'ENERGY, TECH & SUSTAINABILITY': [
      'EV Charger Installer',
      'Insulation & Energy Efficiency Company',
      'PV Installer',
      'Renewable Energy Specialist',
      'Security System Installer',
      'Smart Home & Automation Company',
    ],
    'SPECIALIST TRADES': [
      'Asbestos Removal Specialist',
      'Locksmith',
      'Pest Control Company',
      'Rendering Company',
      'Scaffolding Company',
      'Shop Fitting Company',
      'Swimming Pool & Hot Tub Company',
      'Window & Door Installer',
    ],
    'INDUSTRY LEADERSHIP': [
      'Employer of the Year',
      'Business Leader of the Year',
      'Innovation Award',
      'Apprenticeship Employer of the Year',
      'Community Impact Award',
      'Net Zero & Sustainability Award',
      'Rising Star Award',
    ],
  };

  /* ─────────────────────────────────────────────
     2. SECTOR DISPLAY META
     Controls how each sector renders on home.html:
     image, display name, short description, aria label.
     Add a matching entry here whenever you add a new sector above.
  ───────────────────────────────────────────── */
  const SECTOR_META = {
    'BUILDING & CONSTRUCTION': {
      image: 'building-construction.jpg',
      displayName: 'Building & Construction',
      description: 'From groundworks to roofing, the full build spectrum',
      ariaLabel: 'Building and Construction — From groundworks to roofing, the full build spectrum',
    },
    'MECHANICAL, ELECTRICAL & PLUMBING': {
      image: 'mechanical-electrical-plumbing.jpg',
      displayName: 'Mechanical, Electrical & Plumbing',
      description: "The essential services keeping Britain's homes running",
      ariaLabel: "Mechanical, Electrical and Plumbing — The essential services keeping Britain's homes running",
    },
    'CARPENTRY & JOINERY': {
      image: 'carpentry-joinery.jpg',
      displayName: 'Carpentry & Joinery',
      description: 'Crafting bespoke woodwork with precision and artistry',
      ariaLabel: 'Carpentry and Joinery — Crafting bespoke woodwork with precision and artistry',
    },
    'INTERIOR FIT-OUT & FINISHING': {
      image: 'interior-fitout.jpg',
      displayName: 'Interior Fit-Out & Finishing',
      description: 'Transforming interiors with expert installations',
      ariaLabel: 'Interior Fit-Out and Finishing — Transforming interiors with expert installations',
    },
    'OUTDOOR & LANDSCAPING': {
      image: 'outdoor-landscaping.jpg',
      displayName: 'Outdoor & Landscaping',
      description: 'Creating stunning outdoor spaces across Britain',
      ariaLabel: 'Outdoor and Landscaping — Creating stunning outdoor spaces across Britain',
    },
    'ENERGY, TECH & SUSTAINABILITY': {
      image: 'energy-tech-sustainability.jpg',
      displayName: 'Energy, Tech & Sustainability',
      description: "Powering Britain's green future",
      ariaLabel: "Energy, Tech and Sustainability — Powering Britain's green future",
    },
    'SPECIALIST TRADES': {
      image: 'specialist-trades.jpg',
      displayName: 'Specialist Trades',
      description: 'Niche expertise, exceptional results',
      ariaLabel: 'Specialist Trades — Niche expertise, exceptional results',
    },
    'INDUSTRY LEADERSHIP': {
      image: 'industry-leadership.svg',
      displayName: 'Industry Leadership',
      description: 'Recognising outstanding leadership in the trades',
      ariaLabel: 'Industry Leadership — Recognising outstanding leadership in the trades',
    },
  };

  /* ─────────────────────────────────────────────
     3. REGION DATA — 3-level hierarchy
     country → region group → counties / cities
     Used by:
       - home.html  (regional accordion)
       - submit-entry.js  (country→region→city picker)
       - nominate.js      (country→region→city picker)
     To add a new county or city: add it to the array for its region group.
  ───────────────────────────────────────────── */
  const REGION_DATA = {
    england: {
      Counties: [
        'Bedfordshire',
        'Berkshire',
        'Buckinghamshire',
        'Cambridgeshire',
        'Cheshire',
        'Cornwall',
        'County Durham',
        'Cumbria',
        'Derbyshire',
        'Devon',
        'Dorset',
        'East Sussex',
        'East Yorkshire',
        'Essex',
        'Gloucestershire',
        'Hampshire',
        'Herefordshire',
        'Hertfordshire',
        'Isle of Wight',
        'Kent',
        'Lancashire',
        'Leicestershire',
        'Lincolnshire',
        'Norfolk',
        'Northamptonshire',
        'North Yorkshire',
        'Northumberland',
        'Nottinghamshire',
        'Oxfordshire',
        'Rutland',
        'Shropshire',
        'Somerset',
        'South Yorkshire',
        'Staffordshire',
        'Suffolk',
        'Surrey',
        'Tyne & Wear',
        'Warwickshire',
        'West Sussex',
        'West Yorkshire',
        'Wiltshire',
        'Worcestershire',
      ],
      'London Boroughs': [
        'Bromley',
        'Camden',
        'Croydon',
        'Greenwich',
        'Hackney',
        'Hammersmith & Fulham',
        'Islington',
        'Kensington & Chelsea',
        'Kingston & Richmond',
        'Lambeth',
        'Lewisham',
        'Middlesex',
        'Southwark',
        'Wandsworth',
        'Westminster',
      ],
      Cities: [
        'Birmingham',
        'Bournemouth',
        'Brighton & Hove',
        'Bristol',
        'Coventry',
        'Leeds',
        'Leicester',
        'Liverpool',
        'London',
        'Manchester',
        'Middlesbrough',
        'Newcastle',
        'Nottingham',
        'Reading',
        'Sheffield',
        'Southampton',
      ],
    },
    scotland: {
      'Counties & Areas': [
        'Argyll & Bute',
        'Ayrshire',
        'Central Scotland',
        'Dumfries & Galloway',
        'Dunbartonshire',
        'Fife',
        'Grampian',
        'Highlands',
        'Lanarkshire',
        'Lothian',
        'Renfrewshire',
        'Scottish Borders',
        'Scottish Islands',
        'Tayside',
      ],
      Cities: ['Edinburgh', 'Glasgow'],
    },
    wales: {
      'Counties & Areas': [
        'Carmarthenshire',
        'Ceredigion',
        'Conwy & Denbighshire',
        'Flintshire',
        'Glamorgan',
        'Gwent',
        'Gwynedd & Anglesey',
        'Pembrokeshire',
        'Powys',
        'Wrexham',
      ],
      Cities: ['Cardiff', 'Swansea'],
    },
    'northern-ireland': {
      Belfast: ['Belfast City Centre', 'North Belfast', 'South Belfast', 'East Belfast', 'West Belfast'],
      'Antrim & Newtownabbey': ['Antrim', 'Newtownabbey', 'Ballyclare', 'Randalstown'],
      'Ards & North Down': ['Bangor', 'Newtownards', 'Holywood', 'Comber', 'Donaghadee'],
      'Armagh, Banbridge & Craigavon': ['Armagh', 'Banbridge', 'Craigavon', 'Lurgan', 'Portadown'],
      'Causeway Coast & Glens': ['Coleraine', 'Ballycastle', 'Limavady', 'Ballymoney', 'Portrush'],
      'Derry & Strabane': ['Derry / Londonderry', 'Strabane'],
      'Fermanagh & Omagh': ['Enniskillen', 'Omagh', 'Irvinestown'],
      'Lisburn & Castlereagh': ['Lisburn', 'Castlereagh', 'Dromore'],
      'Mid & East Antrim': ['Ballymena', 'Carrickfergus', 'Larne'],
      'Mid Ulster': ['Cookstown', 'Magherafelt', 'Dungannon', 'Maghera'],
      'Newry, Mourne & Down': ['Newry', 'Newcastle', 'Downpatrick', 'Warrenpoint'],
    },
  };

  /* ─────────────────────────────────────────────
     4. FLAG MAP — location name → /images/flags/<filename>
     Used by home.html regional accordion chips.
     To add a flag: drop the image in /images/flags/ and add the entry here.
  ───────────────────────────────────────────── */
  const FLAG_MAP = {
    // North West
    Cheshire: 'Cheshire.png',
    Cumbria: 'Cumbria.png',
    Lancashire: 'Lancashire.png',
    Liverpool: 'Liverpool County_Merseyside.png',
    Manchester: 'Manchester.png',
    // North East
    'County Durham': 'County Durham.png',
    Northumberland: 'Northumberland.png',
    'Tyne & Wear': 'Tyne & Wear.png',
    Newcastle: 'Newcastle.png',
    Middlesbrough: 'Middlesbrough.png',
    // Yorkshire
    'East Yorkshire': 'East Yorkshire.png',
    'North Yorkshire': 'North Yorkshire.png',
    'South Yorkshire': 'Unofficial_South Yorkshire.png',
    'West Yorkshire': 'West Yorkshire.png',
    Leeds: 'Leeds diocese.png',
    Sheffield: 'Sheffield diocese.png',
    // East Midlands
    Derbyshire: 'Derbyshire.png',
    Leicestershire: 'Leicestershire.png',
    Lincolnshire: 'Lincolnshire.png',
    Northamptonshire: 'Northamptonshire.png',
    Nottinghamshire: 'Nottinghamshire.png',
    Rutland: 'Rutland.png',
    Leicester: 'Leicester diocese.png',
    Nottingham: 'Nottingham diocese.png',
    // West Midlands
    Herefordshire: 'Herefordshire.png',
    Shropshire: 'Shropshire.png',
    Staffordshire: 'Staffordshire.png',
    Warwickshire: 'Warwickshire.png',
    Worcestershire: 'Worcestershire.png',
    Birmingham: 'Birmingham.png',
    Coventry: 'Coventry.png',
    // East of England
    Bedfordshire: 'Bedfordshire.png',
    Cambridgeshire: 'Cambridgeshire.png',
    Essex: 'Essex.png',
    Hertfordshire: 'Hertfordshire.png',
    Norfolk: 'Norfolk.png',
    Suffolk: 'Suffolk.png',
    // London (all boroughs share the London flag; Middlesex has its own)
    London: 'London.png',
    Middlesex: 'Middlesex.png',
    'Barking & Dagenham': 'London.png',
    Barnet: 'London.png',
    Bexley: 'London.png',
    Brent: 'London.png',
    Bromley: 'London.png',
    Camden: 'London.png',
    'City of London': 'London.png',
    Croydon: 'London.png',
    Ealing: 'London.png',
    Enfield: 'London.png',
    Greenwich: 'London.png',
    Hackney: 'London.png',
    'Hammersmith & Fulham': 'London.png',
    Haringey: 'London.png',
    Harrow: 'London.png',
    Havering: 'London.png',
    Hillingdon: 'London.png',
    Hounslow: 'London.png',
    Islington: 'London.png',
    'Kensington & Chelsea': 'London.png',
    'Kingston upon Thames': 'London.png',
    'Kingston & Richmond': 'London.png',
    Lambeth: 'London.png',
    Lewisham: 'London.png',
    Merton: 'London.png',
    Newham: 'London.png',
    Redbridge: 'London.png',
    'Richmond upon Thames': 'London.png',
    Southwark: 'London.png',
    Sutton: 'London.png',
    'Tower Hamlets': 'London.png',
    'Waltham Forest': 'London.png',
    Wandsworth: 'London.png',
    Westminster: 'London.png',
    // South East
    Berkshire: 'Berkshire.png',
    Buckinghamshire: 'Buckinghamshire.png',
    'East Sussex': 'East Sussex.png',
    Hampshire: 'Hampshire.png',
    'Isle of Wight': 'Isle of Wight.png',
    Kent: 'Kent.png',
    Oxfordshire: 'Oxfordshire.png',
    Surrey: 'Surrey.png',
    'West Sussex': 'West Sussex.png',
    'Brighton & Hove': 'Brighton & Hove.png',
    Southampton: 'Southampton.png',
    // South West
    Cornwall: 'Cornwall.png',
    Devon: 'Devon.png',
    Dorset: 'Dorset.png',
    Gloucestershire: 'Gloucestershire.png',
    Somerset: 'Somerset.png',
    Wiltshire: 'Wiltshire.png',
    Bournemouth: 'Bournemouth.png',
    Bristol: 'Bristol.png',
    // Wales
    Cardiff: 'Cardiff.png',
    Swansea: 'Swansea.png',
    Wrexham: 'Wrexham.png',
    Anglesey: 'Anglesey.png',
    Carmarthen: 'Carmarthenshire.png',
    Ceredigion: 'Ceredigion.png',
    Conwy: 'Conwy Wales.png',
    Denbighshire: 'Denbighshire.png',
    Flintshire: 'Flintshire.png',
    Glamorgan: 'Glamorgan.png',
    Gwent: 'Gwent.png',
    Gwynedd: 'Gwynedd.png',
    Pembrokeshire: 'Pembrokeshire.png',
    Powys: 'Powys.png',
    'Conwy & Denbighshire': 'Conwy Wales.png',
    'Gwynedd & Anglesey': 'Gwynedd.png',
    Carmarthenshire: 'Carmarthenshire.png',
    // Scotland (Edinburgh & Glasgow have individual flags; all others use Scotland.png)
    Edinburgh: 'Edinburgh.png',
    Glasgow: 'Glasgow.png',
    Stirling: 'BTA-LOGO-no-date.png',
    Falkirk: 'BTA-LOGO-no-date.png',
    Clackmannanshire: 'BTA-LOGO-no-date.png',
    Lanarkshire: 'BTA-LOGO-no-date.png',
    Dunbartonshire: 'BTA-LOGO-no-date.png',
    Inverness: 'BTA-LOGO-no-date.png',
    'Fort William': 'BTA-LOGO-no-date.png',
    Elgin: 'BTA-LOGO-no-date.png',
    Aviemore: 'BTA-LOGO-no-date.png',
    Wick: 'BTA-LOGO-no-date.png',
    Aberdeen: 'BTA-LOGO-no-date.png',
    Fraserburgh: 'BTA-LOGO-no-date.png',
    Peterhead: 'BTA-LOGO-no-date.png',
    Inverurie: 'BTA-LOGO-no-date.png',
    Dundee: 'BTA-LOGO-no-date.png',
    Perth: 'BTA-LOGO-no-date.png',
    Arbroath: 'BTA-LOGO-no-date.png',
    Kirriemuir: 'BTA-LOGO-no-date.png',
    'St Andrews': 'BTA-LOGO-no-date.png',
    Dunfermline: 'BTA-LOGO-no-date.png',
    Kirkcaldy: 'BTA-LOGO-no-date.png',
    Glenrothes: 'BTA-LOGO-no-date.png',
    Livingston: 'BTA-LOGO-no-date.png',
    Haddington: 'BTA-LOGO-no-date.png',
    Linlithgow: 'BTA-LOGO-no-date.png',
    Paisley: 'BTA-LOGO-no-date.png',
    Ayr: 'BTA-LOGO-no-date.png',
    Kilmarnock: 'BTA-LOGO-no-date.png',
    Hamilton: 'BTA-LOGO-no-date.png',
    Greenock: 'BTA-LOGO-no-date.png',
    Ayrshire: 'BTA-LOGO-no-date.png',
    Renfrewshire: 'BTA-LOGO-no-date.png',
    'Argyll & Bute': 'BTA-LOGO-no-date.png',
    Galashiels: 'BTA-LOGO-no-date.png',
    Hawick: 'BTA-LOGO-no-date.png',
    Jedburgh: 'BTA-LOGO-no-date.png',
    Peebles: 'BTA-LOGO-no-date.png',
    'Scottish Borders': 'BTA-LOGO-no-date.png',
    // Scotland region-level names (used by updated REGION_DATA)
    'Central Scotland': 'BTA-LOGO-no-date.png',
    'Dumfries & Galloway': 'BTA-LOGO-no-date.png',
    Fife: 'BTA-LOGO-no-date.png',
    Grampian: 'BTA-LOGO-no-date.png',
    Highlands: 'BTA-LOGO-no-date.png',
    Lothian: 'BTA-LOGO-no-date.png',
    'Scottish Islands': 'BTA-LOGO-no-date.png',
    Tayside: 'BTA-LOGO-no-date.png',
    Dumfries: 'BTA-LOGO-no-date.png',
    Stranraer: 'BTA-LOGO-no-date.png',
    'Newton Stewart': 'BTA-LOGO-no-date.png',
    Kirkcudbright: 'BTA-LOGO-no-date.png',
    Skye: 'BTA-LOGO-no-date.png',
    Orkney: 'BTA-LOGO-no-date.png',
    Shetland: 'BTA-LOGO-no-date.png',
    Lewis: 'BTA-LOGO-no-date.png',
    Arran: 'BTA-LOGO-no-date.png',
    // English cities without individual flags → England.png placeholder
    Gateshead: 'BTA-LOGO-no-date.png',
    Sunderland: 'BTA-LOGO-no-date.png',
    Bradford: 'BTA-LOGO-no-date.png',
    York: 'BTA-LOGO-no-date.png',
    Hull: 'BTA-LOGO-no-date.png',
    Reading: 'BTA-LOGO-no-date.png',
    // Welsh towns/cities without individual flags → Wales.png placeholder
    Bangor: 'BTA-LOGO-no-date.png',
    Llandudno: 'BTA-LOGO-no-date.png',
    Rhyl: 'BTA-LOGO-no-date.png',
    Holyhead: 'BTA-LOGO-no-date.png',
    Aberystwyth: 'BTA-LOGO-no-date.png',
    Welshpool: 'BTA-LOGO-no-date.png',
    Newtown: 'BTA-LOGO-no-date.png',
    Brecon: 'BTA-LOGO-no-date.png',
    'Llandrindod Wells': 'BTA-LOGO-no-date.png',
    Neath: 'BTA-LOGO-no-date.png',
    'Port Talbot': 'BTA-LOGO-no-date.png',
    Pembroke: 'BTA-LOGO-no-date.png',
    'Milford Haven': 'BTA-LOGO-no-date.png',
    Newport: 'BTA-LOGO-no-date.png',
    'Merthyr Tydfil': 'BTA-LOGO-no-date.png',
    Tredegar: 'BTA-LOGO-no-date.png',
    'Ebbw Vale': 'BTA-LOGO-no-date.png',
    Pontypool: 'BTA-LOGO-no-date.png',
    'Vale of Glamorgan': 'BTA-LOGO-no-date.png',
    Rhondda: 'BTA-LOGO-no-date.png',
    Pontypridd: 'BTA-LOGO-no-date.png',
    Caerphilly: 'BTA-LOGO-no-date.png',
    Bridgend: 'BTA-LOGO-no-date.png',
    // Northern Ireland → United Kingdom.png placeholder
    'Belfast City Centre': 'BTA-LOGO-no-date.png',
    'North Belfast': 'BTA-LOGO-no-date.png',
    'South Belfast': 'BTA-LOGO-no-date.png',
    'East Belfast': 'BTA-LOGO-no-date.png',
    'West Belfast': 'BTA-LOGO-no-date.png',
    Antrim: 'BTA-LOGO-no-date.png',
    Newtownabbey: 'BTA-LOGO-no-date.png',
    Ballyclare: 'BTA-LOGO-no-date.png',
    Randalstown: 'BTA-LOGO-no-date.png',
    Newtownards: 'BTA-LOGO-no-date.png',
    Holywood: 'BTA-LOGO-no-date.png',
    Comber: 'BTA-LOGO-no-date.png',
    Donaghadee: 'BTA-LOGO-no-date.png',
    Armagh: 'BTA-LOGO-no-date.png',
    Banbridge: 'BTA-LOGO-no-date.png',
    Craigavon: 'BTA-LOGO-no-date.png',
    Lurgan: 'BTA-LOGO-no-date.png',
    Portadown: 'BTA-LOGO-no-date.png',
    Coleraine: 'BTA-LOGO-no-date.png',
    Ballycastle: 'BTA-LOGO-no-date.png',
    Limavady: 'BTA-LOGO-no-date.png',
    Ballymoney: 'BTA-LOGO-no-date.png',
    Portrush: 'BTA-LOGO-no-date.png',
    'Derry / Londonderry': 'BTA-LOGO-no-date.png',
    Strabane: 'BTA-LOGO-no-date.png',
    Enniskillen: 'BTA-LOGO-no-date.png',
    Omagh: 'BTA-LOGO-no-date.png',
    Irvinestown: 'BTA-LOGO-no-date.png',
    Lisburn: 'BTA-LOGO-no-date.png',
    Castlereagh: 'BTA-LOGO-no-date.png',
    Dromore: 'BTA-LOGO-no-date.png',
    Ballymena: 'BTA-LOGO-no-date.png',
    Carrickfergus: 'BTA-LOGO-no-date.png',
    Larne: 'BTA-LOGO-no-date.png',
    Cookstown: 'BTA-LOGO-no-date.png',
    Magherafelt: 'BTA-LOGO-no-date.png',
    Dungannon: 'BTA-LOGO-no-date.png',
    Maghera: 'BTA-LOGO-no-date.png',
    Newry: 'BTA-LOGO-no-date.png',
    Downpatrick: 'BTA-LOGO-no-date.png',
    Warrenpoint: 'BTA-LOGO-no-date.png',
  };

  /* ─────────────────────────────────────────────
     5. EXPORT
  ───────────────────────────────────────────── */
  window.BTA_HOME_DATA = {
    sectorCategories: SECTOR_CATEGORIES,
    sectorMeta: SECTOR_META,
    regionData: REGION_DATA,
    flagMap: FLAG_MAP,
  };

  // Backward-compatibility aliases expected by submit-entry.js, nominate.js, config.js
  window.REGION_DATA = REGION_DATA;
  window.SECTORS = Object.keys(SECTOR_CATEGORIES);
  window.STANDARD_CATEGORIES = SECTOR_CATEGORIES;
})();
