/**
 * home-data.js — single source of truth for all public-facing page data.
 *
 * Loaded as a plain <script> (NOT type="module") on home.html, submit-entry.html,
 * and nominate.html, so the data is available synchronously before the page
 * scripts run.  When you add a new sector, category, region, or county/city,
 * update this ONE file — every page updates automatically.
 *
 * Sets:
 *   window.BTA_HOME_DATA      — full structured object (used by home.html)
 *   window.REGION_DATA        — 3-level region hierarchy (submit-entry.js, nominate.js)
 *   window.SECTORS            — flat sector name array (config.js backward compat)
 *   window.STANDARD_CATEGORIES — sector→categories map (config.js backward compat)
 */
(function () {
  'use strict';

  /* ─────────────────────────────────────────────
     1. SECTORS & CATEGORIES
     Mirrors STANDARD_CATEGORIES in config.js.
     To add/remove categories: edit this object.
     To add a new sector: add a new key + entry in SECTOR_META below.
  ───────────────────────────────────────────── */
  const SECTOR_CATEGORIES = {
    'BUILDING & CONSTRUCTION': [
      'Brickwork & Masonry Company',
      'Drainage Company',
      'Extension Company',
      'General Building Company',
      'Groundworks & Foundations Company',
      'Guttering Company',
      'Loft Conversion Company',
      'Maintenance Services',
      'New Build Company',
      'Roofing Company',
      'Structural Engineers',
      'Structural Steelworks',
    ],
    'MECHANICAL, ELECTRICAL & PLUMBING': [
      'Air-Conditioning & Ventilation Company',
      'Electrical Company',
      'Heating Company',
      'Plumbing Company',
      'Underfloor Heating Company',
    ],
    'CARPENTRY & JOINERY': [
      'Cabinet Maker',
      'Carpentry Company',
      'Joinery Company',
      'Staircase Specialist',
      'Timber Windows Installer',
    ],
    'FIT-OUT & FINISHING': [
      'Bathroom Installer',
      'Carpet Fitters',
      'Curtains & Blinds Installer',
      'Drylining Company',
      'Flooring Installer',
      'Home Office Installer',
      'Interior Refurbishment Company',
      'Kitchen Installer',
      'Painting & Decorating Company',
      'Plastering Company',
      'Screeding Company',
      'Tiling Installer',
    ],
    'OUTDOOR & LANDSCAPING': [
      'Decking Company',
      'Driveway & Paving Company',
      'Fencing Installer',
      'Gardening Services',
      'Garden Outbuilding Company',
      'Landscaping & Garden Design Company',
      'Outdoor Lighting & Electrical Company',
      'Tree Surgery Services',
    ],
    'ENERGY, TECH & SUSTAINABILITY': [
      'EV Charger Installer',
      'Insulation & Energy Efficiency Company',
      'PV Installer',
      'Renewable Energy Specialist',
      'Security System Installer',
      'Smart Home & Automation Company',
    ],
    'SPECIALIST TRADES': [
      'Asbestos Removal Specialist',
      'Locksmith',
      'Pest Control Company',
      'Rendering Company',
      'Scaffolding Company',
      'Shop Fitting Company',
      'Swimming Pool & Hot Tub Company',
      'Window & Door Installer',
    ],
    'INDUSTRY LEADERSHIP': [
      'Employer of the Year',
      'Business Leader of the Year',
      'Innovation Award',
      'Apprenticeship Employer of the Year',
      'Community Impact Award',
      'Net Zero & Sustainability Award',
      'Rising Star Award',
    ],
  };

  /* ─────────────────────────────────────────────
     2. SECTOR DISPLAY META
     Controls how each sector renders on home.html:
     image, display name, short description, aria label.
     Add a matching entry here whenever you add a new sector above.
  ───────────────────────────────────────────── */
  const SECTOR_META = {
    'BUILDING & CONSTRUCTION': {
      image: 'building-construction.jpg',
      displayName: 'Building & Construction',
      description: 'Extensions, Roofing, Maintenance, Groundworks, Loft Conversions, Drainage & more...',
      ariaLabel:
        'Building and Construction — Extensions, Roofing, Maintenance, Groundworks, Loft Conversions, Drainage & more',
    },
    'MECHANICAL, ELECTRICAL & PLUMBING': {
      image: 'mechanical-electrical-plumbing.jpg',
      displayName: 'Mechanical, Engineering & Plumbing',
      description: 'Electrics, Heating, Plumbing, Air-Conditioning & more…',
      ariaLabel: 'Mechanical, Engineering and Plumbing — Electrics, Heating, Plumbing, Air-Conditioning & more',
    },
    'CARPENTRY & JOINERY': {
      image: 'carpentry-joinery.jpg',
      displayName: 'Carpentry & Joinery',
      description: 'Bespoke Woodworking: Cabinets, Staircases, Timber Windows & more…',
      ariaLabel: 'Carpentry and Joinery — Bespoke Woodworking: Cabinets, Staircases, Timber Windows & more',
    },
    'FIT-OUT & FINISHING': {
      image: 'interior-fitout.jpg',
      displayName: 'Fit-Out & Finishing',
      description: 'Bathrooms, Kitchens, Carpets & Flooring, Painting & Decorating, Plastering, Tiling & more…',
      ariaLabel:
        'Fit-Out and Finishing — Bathrooms, Kitchens, Carpets & Flooring, Painting & Decorating, Plastering, Tiling & more',
    },
    'OUTDOOR & LANDSCAPING': {
      image: 'outdoor-landscaping.jpg',
      displayName: 'Outdoors & Landscaping',
      description: 'Gardening, Driveways, Fencing, Decking, Tree Surgery & more',
      ariaLabel: 'Outdoors and Landscaping — Gardening, Driveways, Fencing, Decking, Tree Surgery & more',
    },
    'ENERGY, TECH & SUSTAINABILITY': {
      image: 'energy-tech-sustainability.jpg',
      displayName: 'Tech & Green Energy',
      description: 'EV Chargers, Renewable Energy, Security Systems, Smart Homes & more',
      ariaLabel: 'Tech and Green Energy — EV Chargers, Renewable Energy, Security Systems, Smart Homes & more',
    },
    'SPECIALIST TRADES': {
      image: 'specialist-trades.jpg',
      displayName: 'Specialist Trades',
      description: 'Locksmiths, Pest Control, Scaffolding, Windows & Doors & more',
      ariaLabel: 'Specialist Trades — Locksmiths, Pest Control, Scaffolding, Windows & Doors & more',
    },
    'INDUSTRY LEADERSHIP': {
      image: 'industry-leadership.jpg',
      displayName: 'Industry Leadership',
      description: 'Recognising extraordinary individuals',
      ariaLabel: 'Industry Leadership — Recognising extraordinary individuals',
    },
  };

  /* ─────────────────────────────────────────────
     3. REGION DATA — 3-level hierarchy
     country → region group → counties / cities
     Used by:
       - home.html  (regional accordion)
       - submit-entry.js  (country→region→city picker)
       - nominate.js      (country→region→city picker)
     To add a new county or city: add it to the array for its region group.
  ───────────────────────────────────────────── */
  const REGION_DATA = {
    england: {
      Counties: [
        'Bedfordshire',
        'Berkshire',
        'Buckinghamshire',
        'Cambridgeshire',
        'Cheshire',
        'Cornwall',
        'County Durham',
        'Cumbria',
        'Derbyshire',
        'Devon',
        'Dorset',
        'East Sussex',
        'East Yorkshire',
        'Essex',
        'Gloucestershire',
        'Hampshire',
        'Herefordshire',
        'Hertfordshire',
        'Isle of Wight',
        'Kent',
        'Lancashire',
        'Leicestershire',
        'Lincolnshire',
        'Norfolk',
        'Northamptonshire',
        'North Yorkshire',
        'Northumberland',
        'Nottinghamshire',
        'Oxfordshire',
        'Rutland',
        'Shropshire',
        'Somerset',
        'South Yorkshire',
        'Staffordshire',
        'Suffolk',
        'Surrey',
        'Tyne & Wear',
        'Warwickshire',
        'West Sussex',
        'West Yorkshire',
        'Wiltshire',
        'Worcestershire',
      ],
      Cities: [
        'Birmingham',
        'Bournemouth',
        'Brighton & Hove',
        'Bristol',
        'Coventry',
        'Leeds',
        'Leicester',
        'Liverpool',
        'Manchester',
        'Middlesbrough',
        'Newcastle',
        'Nottingham',
        'Reading',
        'Sheffield',
        'Southampton',
      ],
      'London Boroughs': [
        'Barking & Dagenham',
        'Barnet',
        'Bexley',
        'Brent',
        'Bromley',
        'Camden',
        'City of London',
        'Croydon',
        'Ealing',
        'Enfield',
        'Greenwich',
        'Hackney',
        'Hammersmith & Fulham',
        'Haringey',
        'Harrow',
        'Havering',
        'Hillingdon',
        'Hounslow',
        'Islington',
        'Kensington & Chelsea',
        'Kingston & Richmond',
        'Lambeth',
        'Lewisham',
        'Merton',
        'Middlesex',
        'Newham',
        'Redbridge',
        'Richmond upon Thames',
        'Southwark',
        'Sutton',
        'Tower Hamlets',
        'Waltham Forest',
        'Wandsworth',
        'Westminster',
      ],
    },
    scotland: {
      'Counties & Areas': [
        'Argyll & Bute',
        'Ayrshire',
        'Central Scotland',
        'Dumfries & Galloway',
        'Dunbartonshire',
        'Fife',
        'Grampian',
        'Highlands',
        'Lanarkshire',
        'Lothian',
        'Renfrewshire',
        'Scottish Borders',
        'Scottish Islands',
        'Tayside',
      ],
      Cities: ['Edinburgh', 'Glasgow'],
    },
    wales: {
      'Counties & Areas': [
        'Carmarthenshire',
        'Ceredigion',
        'Conwy & Denbighshire',
        'Flintshire',
        'Glamorgan',
        'Gwent',
        'Gwynedd & Anglesey',
        'Pembrokeshire',
        'Powys',
        'Wrexham',
      ],
      Cities: ['Cardiff', 'Swansea'],
    },
    'northern-ireland': {
      Belfast: ['Belfast City Centre', 'North Belfast', 'South Belfast', 'East Belfast', 'West Belfast'],
      'Antrim & Newtownabbey': ['Antrim', 'Newtownabbey', 'Ballyclare', 'Randalstown'],
      'Ards & North Down': ['Bangor', 'Newtownards', 'Holywood', 'Comber', 'Donaghadee'],
      'Armagh, Banbridge & Craigavon': ['Armagh', 'Banbridge', 'Craigavon', 'Lurgan', 'Portadown'],
      'Causeway Coast & Glens': ['Coleraine', 'Ballycastle', 'Limavady', 'Ballymoney', 'Portrush'],
      'Derry & Strabane': ['Derry / Londonderry', 'Strabane'],
      'Fermanagh & Omagh': ['Enniskillen', 'Omagh', 'Irvinestown'],
      'Lisburn & Castlereagh': ['Lisburn', 'Castlereagh', 'Dromore'],
      'Mid & East Antrim': ['Ballymena', 'Carrickfergus', 'Larne'],
      'Mid Ulster': ['Cookstown', 'Magherafelt', 'Dungannon', 'Maghera'],
      'Newry, Mourne & Down': ['Newry', 'Newcastle', 'Downpatrick', 'Warrenpoint'],
    },
  };

  /* ─────────────────────────────────────────────
     4. FLAG MAP — location name → /images/flags/<filename>
     Used by home.html regional accordion chips.
     To add a flag: drop the image in /images/flags/ and add the entry here.
  ───────────────────────────────────────────── */
  const FLAG_MAP = {
    // North West
    Cheshire: 'Cheshire.png',
    Cumbria: 'Cumbria.png',
    Lancashire: 'Lancashire.png',
    Liverpool: 'Liverpool County_Merseyside.png',
    Manchester: 'Manchester.png',
    // North East
    'County Durham': 'County Durham.png',
    Northumberland: 'Northumberland.png',
    'Tyne & Wear': 'Tyne & Wear.png',
    Newcastle: 'Newcastle.png',
    Middlesbrough: 'Middlesbrough.png',
    // Yorkshire
    'East Yorkshire': 'East Yorkshire.png',
    'North Yorkshire': 'North Yorkshire.png',
    'South Yorkshire': 'Unofficial_South Yorkshire.png',
    'West Yorkshire': 'West Yorkshire.png',
    Leeds: 'Leeds diocese.png',
    Sheffield: 'Sheffield diocese.png',
    // East Midlands
    Derbyshire: 'Derbyshire.png',
    Leicestershire: 'Leicestershire.png',
    Lincolnshire: 'Lincolnshire.png',
    Northamptonshire: 'Northamptonshire.png',
    Nottinghamshire: 'Nottinghamshire.png',
    Rutland: 'Rutland.png',
    Leicester: 'Leicester diocese.png',
    Nottingham: 'Nottingham diocese.png',
    // West Midlands
    Herefordshire: 'Herefordshire.png',
    Shropshire: 'Shropshire.png',
    Staffordshire: 'Staffordshire.png',
    Warwickshire: 'Warwickshire.png',
    Worcestershire: 'Worcestershire.png',
    Birmingham: 'Birmingham.png',
    Coventry: 'Coventry.png',
    // East of England
    Bedfordshire: 'Bedfordshire.png',
    Cambridgeshire: 'Cambridgeshire.png',
    Essex: 'Essex.png',
    Hertfordshire: 'Hertfordshire.png',
    Norfolk: 'Norfolk.png',
    Suffolk: 'Suffolk.png',
    // London (all boroughs share the London flag; Middlesex has its own)
    London: 'London.png',
    Middlesex: 'Middlesex.png',
    'Barking & Dagenham': 'London.png',
    Barnet: 'London.png',
    Bexley: 'London.png',
    Brent: 'London.png',
    Bromley: 'London.png',
    Camden: 'London.png',
    'City of London': 'London.png',
    Croydon: 'London.png',
    Ealing: 'London.png',
    Enfield: 'London.png',
    Greenwich: 'London.png',
    Hackney: 'London.png',
    'Hammersmith & Fulham': 'London.png',
    Haringey: 'London.png',
    Harrow: 'London.png',
    Havering: 'London.png',
    Hillingdon: 'London.png',
    Hounslow: 'London.png',
    Islington: 'London.png',
    'Kensington & Chelsea': 'London.png',
    'Kingston & Richmond': 'London.png',
    Lambeth: 'London.png',
    Lewisham: 'London.png',
    Merton: 'London.png',
    Newham: 'London.png',
    Redbridge: 'London.png',
    'Richmond upon Thames': 'London.png',
    Southwark: 'London.png',
    Sutton: 'London.png',
    'Tower Hamlets': 'London.png',
    'Waltham Forest': 'London.png',
    Wandsworth: 'London.png',
    Westminster: 'London.png',
    // South East
    Berkshire: 'Berkshire.png',
    Buckinghamshire: 'Buckinghamshire.png',
    'East Sussex': 'East Sussex.png',
    Hampshire: 'Hampshire.png',
    'Isle of Wight': 'Isle of Wight.png',
    Kent: 'Kent.png',
    Oxfordshire: 'Oxfordshire.png',
    Surrey: 'Surrey.png',
    'West Sussex': 'West Sussex.png',
    'Brighton & Hove': 'Brighton & Hove.png',
    Southampton: 'Southampton.png',
    // South West
    Cornwall: 'Cornwall.png',
    Devon: 'Devon.png',
    Dorset: 'Dorset.png',
    Gloucestershire: 'Gloucestershire.png',
    Somerset: 'Somerset.png',
    Wiltshire: 'Wiltshire.png',
    Bournemouth: 'Bournemouth.png',
    Bristol: 'Bristol.png',
    // Wales
    Cardiff: 'Cardiff.png',
    Swansea: 'Swansea.png',
    Wrexham: 'Wrexham.png',
    Anglesey: 'Anglesey.png',
    Carmarthen: 'Carmarthenshire.png',
    Ceredigion: 'Ceredigion.png',
    Conwy: 'Conwy Wales.png',
    Denbighshire: 'Denbighshire.png',
    Flintshire: 'Flintshire.png',
    Glamorgan: 'Glamorgan.png',
    Gwent: 'Gwent.png',
    Gwynedd: 'Gwynedd.png',
    Pembrokeshire: 'Pembrokeshire.png',
    Powys: 'Powys.png',
    'Conwy & Denbighshire': 'Conwy Wales.png',
    'Gwynedd & Anglesey': 'Gwynedd.png',
    Carmarthenshire: 'Carmarthenshire.png',
    // Scotland (Edinburgh & Glasgow have individual flags; all others use Scotland.png)
    Edinburgh: 'Edinburgh.png',
    Glasgow: 'Glasgow.png',
    Stirling: 'BTA_Corporate_Horizontal-gold-white.png',
    Falkirk: 'BTA_Corporate_Horizontal-gold-white.png',
    Clackmannanshire: 'BTA_Corporate_Horizontal-gold-white.png',
    Lanarkshire: 'BTA_Corporate_Horizontal-gold-white.png',
    Dunbartonshire: 'BTA_Corporate_Horizontal-gold-white.png',
    Inverness: 'BTA_Corporate_Horizontal-gold-white.png',
    'Fort William': 'BTA_Corporate_Horizontal-gold-white.png',
    Elgin: 'BTA_Corporate_Horizontal-gold-white.png',
    Aviemore: 'BTA_Corporate_Horizontal-gold-white.png',
    Wick: 'BTA_Corporate_Horizontal-gold-white.png',
    Aberdeen: 'BTA_Corporate_Horizontal-gold-white.png',
    Fraserburgh: 'BTA_Corporate_Horizontal-gold-white.png',
    Peterhead: 'BTA_Corporate_Horizontal-gold-white.png',
    Inverurie: 'BTA_Corporate_Horizontal-gold-white.png',
    Dundee: 'BTA_Corporate_Horizontal-gold-white.png',
    Perth: 'BTA_Corporate_Horizontal-gold-white.png',
    Arbroath: 'BTA_Corporate_Horizontal-gold-white.png',
    Kirriemuir: 'BTA_Corporate_Horizontal-gold-white.png',
    'St Andrews': 'BTA_Corporate_Horizontal-gold-white.png',
    Dunfermline: 'BTA_Corporate_Horizontal-gold-white.png',
    Kirkcaldy: 'BTA_Corporate_Horizontal-gold-white.png',
    Glenrothes: 'BTA_Corporate_Horizontal-gold-white.png',
    Livingston: 'BTA_Corporate_Horizontal-gold-white.png',
    Haddington: 'BTA_Corporate_Horizontal-gold-white.png',
    Linlithgow: 'BTA_Corporate_Horizontal-gold-white.png',
    Paisley: 'BTA_Corporate_Horizontal-gold-white.png',
    Ayr: 'BTA_Corporate_Horizontal-gold-white.png',
    Kilmarnock: 'BTA_Corporate_Horizontal-gold-white.png',
    Hamilton: 'BTA_Corporate_Horizontal-gold-white.png',
    Greenock: 'BTA_Corporate_Horizontal-gold-white.png',
    Ayrshire: 'BTA_Corporate_Horizontal-gold-white.png',
    Renfrewshire: 'BTA_Corporate_Horizontal-gold-white.png',
    'Argyll & Bute': 'BTA_Corporate_Horizontal-gold-white.png',
    Galashiels: 'BTA_Corporate_Horizontal-gold-white.png',
    Hawick: 'BTA_Corporate_Horizontal-gold-white.png',
    Jedburgh: 'BTA_Corporate_Horizontal-gold-white.png',
    Peebles: 'BTA_Corporate_Horizontal-gold-white.png',
    'Scottish Borders': 'BTA_Corporate_Horizontal-gold-white.png',
    // Scotland region-level names (used by updated REGION_DATA)
    'Central Scotland': 'BTA_Corporate_Horizontal-gold-white.png',
    'Dumfries & Galloway': 'BTA_Corporate_Horizontal-gold-white.png',
    Fife: 'BTA_Corporate_Horizontal-gold-white.png',
    Grampian: 'BTA_Corporate_Horizontal-gold-white.png',
    Highlands: 'BTA_Corporate_Horizontal-gold-white.png',
    Lothian: 'BTA_Corporate_Horizontal-gold-white.png',
    'Scottish Islands': 'BTA_Corporate_Horizontal-gold-white.png',
    Tayside: 'BTA_Corporate_Horizontal-gold-white.png',
    Dumfries: 'BTA_Corporate_Horizontal-gold-white.png',
    Stranraer: 'BTA_Corporate_Horizontal-gold-white.png',
    'Newton Stewart': 'BTA_Corporate_Horizontal-gold-white.png',
    Kirkcudbright: 'BTA_Corporate_Horizontal-gold-white.png',
    Skye: 'BTA_Corporate_Horizontal-gold-white.png',
    Orkney: 'BTA_Corporate_Horizontal-gold-white.png',
    Shetland: 'BTA_Corporate_Horizontal-gold-white.png',
    Lewis: 'BTA_Corporate_Horizontal-gold-white.png',
    Arran: 'BTA_Corporate_Horizontal-gold-white.png',
    // English cities without individual flags → England.png placeholder
    Gateshead: 'BTA_Corporate_Horizontal-gold-white.png',
    Sunderland: 'BTA_Corporate_Horizontal-gold-white.png',
    Bradford: 'BTA_Corporate_Horizontal-gold-white.png',
    York: 'BTA_Corporate_Horizontal-gold-white.png',
    Hull: 'BTA_Corporate_Horizontal-gold-white.png',
    Reading: 'BTA_Corporate_Horizontal-gold-white.png',
    // Welsh towns/cities without individual flags → Wales.png placeholder
    Bangor: 'BTA_Corporate_Horizontal-gold-white.png',
    Llandudno: 'BTA_Corporate_Horizontal-gold-white.png',
    Rhyl: 'BTA_Corporate_Horizontal-gold-white.png',
    Holyhead: 'BTA_Corporate_Horizontal-gold-white.png',
    Aberystwyth: 'BTA_Corporate_Horizontal-gold-white.png',
    Welshpool: 'BTA_Corporate_Horizontal-gold-white.png',
    Newtown: 'BTA_Corporate_Horizontal-gold-white.png',
    Brecon: 'BTA_Corporate_Horizontal-gold-white.png',
    'Llandrindod Wells': 'BTA_Corporate_Horizontal-gold-white.png',
    Neath: 'BTA_Corporate_Horizontal-gold-white.png',
    'Port Talbot': 'BTA_Corporate_Horizontal-gold-white.png',
    Pembroke: 'BTA_Corporate_Horizontal-gold-white.png',
    'Milford Haven': 'BTA_Corporate_Horizontal-gold-white.png',
    Newport: 'BTA_Corporate_Horizontal-gold-white.png',
    'Merthyr Tydfil': 'BTA_Corporate_Horizontal-gold-white.png',
    Tredegar: 'BTA_Corporate_Horizontal-gold-white.png',
    'Ebbw Vale': 'BTA_Corporate_Horizontal-gold-white.png',
    Pontypool: 'BTA_Corporate_Horizontal-gold-white.png',
    'Vale of Glamorgan': 'BTA_Corporate_Horizontal-gold-white.png',
    Rhondda: 'BTA_Corporate_Horizontal-gold-white.png',
    Pontypridd: 'BTA_Corporate_Horizontal-gold-white.png',
    Caerphilly: 'BTA_Corporate_Horizontal-gold-white.png',
    Bridgend: 'BTA_Corporate_Horizontal-gold-white.png',
    // Northern Ireland → United Kingdom.png placeholder
    'Belfast City Centre': 'BTA_Corporate_Horizontal-gold-white.png',
    'North Belfast': 'BTA_Corporate_Horizontal-gold-white.png',
    'South Belfast': 'BTA_Corporate_Horizontal-gold-white.png',
    'East Belfast': 'BTA_Corporate_Horizontal-gold-white.png',
    'West Belfast': 'BTA_Corporate_Horizontal-gold-white.png',
    Antrim: 'BTA_Corporate_Horizontal-gold-white.png',
    Newtownabbey: 'BTA_Corporate_Horizontal-gold-white.png',
    Ballyclare: 'BTA_Corporate_Horizontal-gold-white.png',
    Randalstown: 'BTA_Corporate_Horizontal-gold-white.png',
    Newtownards: 'BTA_Corporate_Horizontal-gold-white.png',
    Holywood: 'BTA_Corporate_Horizontal-gold-white.png',
    Comber: 'BTA_Corporate_Horizontal-gold-white.png',
    Donaghadee: 'BTA_Corporate_Horizontal-gold-white.png',
    Armagh: 'BTA_Corporate_Horizontal-gold-white.png',
    Banbridge: 'BTA_Corporate_Horizontal-gold-white.png',
    Craigavon: 'BTA_Corporate_Horizontal-gold-white.png',
    Lurgan: 'BTA_Corporate_Horizontal-gold-white.png',
    Portadown: 'BTA_Corporate_Horizontal-gold-white.png',
    Coleraine: 'BTA_Corporate_Horizontal-gold-white.png',
    Ballycastle: 'BTA_Corporate_Horizontal-gold-white.png',
    Limavady: 'BTA_Corporate_Horizontal-gold-white.png',
    Ballymoney: 'BTA_Corporate_Horizontal-gold-white.png',
    Portrush: 'BTA_Corporate_Horizontal-gold-white.png',
    'Derry / Londonderry': 'BTA_Corporate_Horizontal-gold-white.png',
    Strabane: 'BTA_Corporate_Horizontal-gold-white.png',
    Enniskillen: 'BTA_Corporate_Horizontal-gold-white.png',
    Omagh: 'BTA_Corporate_Horizontal-gold-white.png',
    Irvinestown: 'BTA_Corporate_Horizontal-gold-white.png',
    Lisburn: 'BTA_Corporate_Horizontal-gold-white.png',
    Castlereagh: 'BTA_Corporate_Horizontal-gold-white.png',
    Dromore: 'BTA_Corporate_Horizontal-gold-white.png',
    Ballymena: 'BTA_Corporate_Horizontal-gold-white.png',
    Carrickfergus: 'BTA_Corporate_Horizontal-gold-white.png',
    Larne: 'BTA_Corporate_Horizontal-gold-white.png',
    Cookstown: 'BTA_Corporate_Horizontal-gold-white.png',
    Magherafelt: 'BTA_Corporate_Horizontal-gold-white.png',
    Dungannon: 'BTA_Corporate_Horizontal-gold-white.png',
    Maghera: 'BTA_Corporate_Horizontal-gold-white.png',
    Newry: 'BTA_Corporate_Horizontal-gold-white.png',
    Downpatrick: 'BTA_Corporate_Horizontal-gold-white.png',
    Warrenpoint: 'BTA_Corporate_Horizontal-gold-white.png',
  };

  /* ─────────────────────────────────────────────
     5. EXPORT
  ───────────────────────────────────────────── */
  window.BTA_HOME_DATA = {
    sectorCategories: SECTOR_CATEGORIES,
    sectorMeta: SECTOR_META,
    regionData: REGION_DATA,
    flagMap: FLAG_MAP,
  };

  // Backward-compatibility aliases expected by submit-entry.js, nominate.js, config.js
  window.REGION_DATA = REGION_DATA;
  window.LONDON_BOROUGHS = [
    'Barking & Dagenham',
    'Barnet',
    'Bexley',
    'Brent',
    'Bromley',
    'Camden',
    'City of London',
    'Croydon',
    'Ealing',
    'Enfield',
    'Greenwich',
    'Hackney',
    'Hammersmith & Fulham',
    'Haringey',
    'Harrow',
    'Havering',
    'Hillingdon',
    'Hounslow',
    'Islington',
    'Kensington & Chelsea',
    'Kingston & Richmond',
    'Lambeth',
    'Lewisham',
    'Merton',
    'Middlesex',
    'Newham',
    'Redbridge',
    'Richmond upon Thames',
    'Southwark',
    'Sutton',
    'Tower Hamlets',
    'Waltham Forest',
    'Wandsworth',
    'Westminster',
  ];
  window.SECTORS = Object.keys(SECTOR_CATEGORIES);
  window.STANDARD_CATEGORIES = SECTOR_CATEGORIES;
})();
